      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add sitesFull.json
          git add sitesLite.json

          if git diff --cached --quiet; then
            echo "No changes, nothing to commit."
            exit 0
          fi

          git commit -m "Update sitesFull & sitesLite [skip ci]"
          git push
